apiVersion: registry.kubecontroller.io/v1alpha1
kind: Registry
metadata:
  name: nginx-with-sbom
  namespace: default
spec:
  url: "https://registry-1.docker.io"
  repository: "library/nginx"
  scanInterval: 600

  # Tag filtering - scan only stable versions
  tagFilter:
    include: "^1\\.(2[4-6]|27)\\..*$"  # nginx 1.24.x - 1.27.x
    limit: 3
    sortBy: "newest"

  # Scan configuration
  scanConfig:
    timeout: "60s"
    retryAttempts: 3
    retryDelay: "10s"
    concurrency: 2

  # Vulnerability scanning
  vulnerabilityScanning:
    enabled: true
    scanner: "trivy"
    scanInterval: 3600
    severityThreshold: "MEDIUM"
    ignoreUnfixed: false

  # SBOM generation - NEW FEATURE
  sbomGeneration:
    enabled: true
    format: "syft-json"          # Options: spdx-json, cyclonedx-json, syft-json
    includeLicenses: true        # Include license information
    scanInterval: 3600           # Regenerate SBOM every hour
    # tags:                      # Optional: specific tags to scan
    #   - "1.27.1"
    #   - "1.26.2"
