# Vulnerability scanning with Trivy
#
# Requires Trivy installed on the operator host/container
# https://trivy.dev/
#
apiVersion: registry.kubecontroller.io/v1alpha1
kind: Registry
metadata:
  name: nginx-secure
spec:
  url: https://registry-1.docker.io
  repository: library/nginx
  scanInterval: 300
  tagFilter:
    include: "^1\\.2[4-6]"  # nginx 1.24.x - 1.26.x
    limit: 5
  vulnerabilityScanning:
    enabled: true
    scanner: trivy
    scanInterval: 3600              # scan for CVEs every hour
    severityThreshold: HIGH         # report HIGH and CRITICAL only
    ignoreUnfixed: true             # skip CVEs without a fix
    # tags:                         # optional: only scan specific tags
    #   - "1.25.3"
    #   - "1.26.0"
