---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-operator
  namespace: d8-registry-operator
  {{- include "helm_lib_module_labels" (list . (dict "app" "registry-operator")) | nindent 2 }}
